FROM alpine:latest

RUN apk update \
	&& apk add --no-cache wget \
	&& apk add --no-cache nginx openrc openssl openssh \
	&& apk add --no-cache php-fpm php7-common php7-session php7-iconv php7-json \
	php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi \
	fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix \
	php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom

COPY . /APP
WORKDIR /APP

# can't run nginx, if this file no exist
RUN mkdir /run/nginx;

ADD srcs/nginx.conf /etc/nginx/conf.d/default.conf

# RUN mkdir /var/www/wordpress \
# 	&& cp /etc/resolv.conf . \
# 	&& echo "nameserver 8.8.8.8" > /etc/resolv.conf \
# 	&& wget https://wordpress.org/latest.tar.gz -P /var/www/wordpress/ \
# 	&& tar -xzvf /var/www/wordpress/latest.tar.gz -C /var/www/wordpress/ \
# 	&& rm /var/www/wordpress/latest.tar.gz
# RUN cat ./resolv.conf > /etc/resolv.conf && rm ./resolv.conf

# at home /etc/resolv.conf : nameserver 192.168.65.5
RUN mkdir /var/www/wordpress \
	&& wget https://wordpress.org/latest.tar.gz -P /var/www/wordpress  \
	&& tar -xzvf /var/www/wordpress/latest.tar.gz -C /var/www/wordpress \
	&& rm /var/www/wordpress/latest.tar.gz

EXPOSE 5050

CMD ["/bin/sh", "./srcs/init.sh"]