apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: svc_wordpress
        imagePullPolicy: Never
        env:
          - name: WP_PASS
            value: "wppass"
        ports:
        - containerPort: 5050
          name: wordpress-http
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  type: LoadBalancer
  ports:
  - port: 5050
    targetPort: 5050
    nodePort: 5050
    name: wordpress-http