# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaye <kaye@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/28 21:33:25 by kaye              #+#    #+#              #
#    Updated: 2021/04/29 11:33:16 by kaye             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

COPY . /APP
WORKDIR /APP

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&& apk update \
	&& apk add --no-cache openrc wget

EXPOSE 3000