# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaye <kaye@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/28 21:33:25 by kaye              #+#    #+#              #
#    Updated: 2021/05/12 14:31:36 by kaye             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

COPY . /APP
WORKDIR /APP

# VOLUME /sys/fs/cgroup

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&& apk update \
	&& apk add --no-cache grafana --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing
	&& apk add --no-cache openrc wget telegraf vim

# telegraf config
RUN mkdir /etc/telegraf/
ADD ./srcs/telegraf.conf /etc/telegraf/telegraf.conf

EXPOSE 3000

CMD ["/bin/sh", "./srcs/init.sh"]