apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: ftps
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: ftps-container
        image: svc_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          protocol: TCP
          name: ftps-port
        volumeMounts:
        - mountPath: "/home/vsftpd"
          name: ftps
        env:
        - name: FTP_USER
          value: "user"
        - name: FTP_PASS
          value: "userpass"
        #- name: PASV_ADDRESS
        #  value: "127.0.0.1"
        #- name: PASV_MIN_PORT
        #  value: "21100"
        #- name: PASV_MAX_PORT
        #  value: "21110"
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: universal-ip
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftps
    protocol: TCP
    port: 21
    targetPort: 21