apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: svc_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30000
        - containerPort: 30001
        - containerPort: 30002
        - containerPort: 30003
        - containerPort: 30004
        - containerPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    # metallb.universe.tf/allow-shared-ip: <key> : use the same IP address for each service with the same key
    metallb.universe.tf/allow-shared-ip: universal-ip
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 20
    targetPort: 20
    nodePort: 20
    name: ftps-port-20
  - port: 21
    targetPort: 21
    nodePort: 21
    name: ftps-port-21
  - port: 30000
    targetPort: 30000
    nodePort: 30000
    name: ftps-pasif-port
  - port: 30001
    targetPort: 30001
    nodePort: 30001
    name: ftps-pasif-port
  - port: 30002
    targetPort: 30002
    nodePort: 30002
    name: ftps-pasif-port
  - port: 30003
    targetPort: 30003
    nodePort: 30003
    name: ftps-pasif-port
  - port: 30004
    targetPort: 30004
    nodePort: 30004
    name: ftps-pasif-port
  - port: 30005
    targetPort: 30005
    nodePort: 30005
    name: ftps-pasif-port