# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaye <kaye@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/05/11 10:43:48 by kaye              #+#    #+#              #
#    Updated: 2021/05/12 12:53:48 by kaye             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

COPY . /APP
WORKDIR /APP

# VOLUME /sys/fs/cgroup

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&& apk update \
	&& apk add --no-cache telegraf openrc wget

RUN mv /APP/srcs/telegraf.conf /etc/telegraf.conf.d

# telegraf config
ADD ./srcs/telegraf.conf /etc/telegraf/telegraf.conf

EXPOSE 8125

CMD ["/bin/sh", "./srcs/init.sh"]