# apiVersion: v1
# kind: Service
# metadata:
#   name: telegraf
#   labels:
#     app: telegraf
# spec:
#   type: ClusterIP
#   selector:
#     app: telegraf
#   ports:
#   - port: 8125
#     targetPort: 8125
#     name: telegraf
# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: telegraf
# spec:
#   selector:
#     matchLabels:
#       app: telegraf
#   serviceName: telegraf
#   template:
#     metadata:
#       labels:
#         app: telegraf
#     spec:
#       containers:
#       - name: telegraf
#         image: svc_telegraf
#         imagePullPolicy: Never
#         ports:
#         - containerPort: 8125
#           name: telegraf
#         # livenessProbe:
#         #   exec:
#         #     command:
#         #       - sh
#         #       - /APP/srcs/livenessprobe.sh
#         volumeMounts:
#         - name: telegraf
#           mountPath: "/var/run/docker.sock"
#       volumes:
#       - name: telegraf
#         persistentVolumeClaim:
#           claimName: telegraf
#       - ./etc/telegraf
#       - /var/run/docker.sock:/var/run/docker.sock
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: telegraf
#   labels:
#     app: telegraf
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: telegraf
#   labels:
#     type: telegraf
# spec:
#   storageClassName: telegraf
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/var/run/docker.sock"
apiVersion: v1
kind: PersistentVolume
metadata:
  name: telegraf
  labels:
    type: local
spec:
  storageClassName: telegraf
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: telegraf
  labels:
    app: telegraf
spec:
  storageClassName: telegraf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: telegraf
spec:
    selector:
        matchLabels:
            app: telegraf
    template:
        metadata:
            labels:
                app: telegraf
        spec:
            containers:
                - image: svc_telegraf
                  name: telegraf
                  imagePullPolicy: Never
                  volumeMounts:
                      - name: telegraf
                        mountPath: "/var/run/docker.sock"
            volumes:
                - name: telegraf
                  persistentVolumeClaim:
                    claimName: telegraf
