# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kaye <kaye@student.42.fr>                  +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/04/28 21:33:35 by kaye              #+#    #+#              #
#    Updated: 2021/05/12 12:54:58 by kaye             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:latest

COPY . /APP
WORKDIR /APP

# VOLUME /sys/fs/cgroup

RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf \
	&& apk update \
	&& apk add --no-cache influxdb openrc telegraf

# telegraf config
ADD ./srcs/telegraf.conf /etc/telegraf/telegraf.conf

EXPOSE 8086

CMD ["/bin/sh", "./srcs/init.sh"]